# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Sample label"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World! This is from the sample.bookshop.yml `blueprint/text` field"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  text: "This is from the sample.bookshop.yml `preview` field"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
